// Tabler Icons - Bold, professional, 5000+ icons
import {
  IconDatabase,
  IconPhone,
  IconSparkles,
  IconBolt,
  IconWorld,
  IconGitBranch,
  IconStack2,
  IconRobot,
  IconCode,
  IconDeviceMobile,
  IconMenu2,
  IconX,
  IconHome,
  IconInfoCircle,
  IconMail,
  IconSun,
  IconMoon,
  IconChevronRight,
  IconChevronDown,
  IconArrowRight,
  IconCheck,
  IconCalendar,
  IconClock,
  IconUser,
  IconUsers,
  IconSettings,
  IconSearch,
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconDownload,
  IconUpload,
  IconLink,
  IconExternalLink,
  IconCopy,
  IconRefresh,
  IconSend,
  IconHeart,
  IconStar,
  IconBell,
  IconFilter,
  IconArrowsSort,
  IconLayoutGrid,
  IconList,
  IconEye,
  IconEyeOff,
  IconLock,
  IconLockOpen,
  IconShield,
  IconAlertTriangle,
  IconAlertCircle,
  IconHelpCircle,
  IconCircleCheck,
  IconCircleX,
} from '@tabler/icons-react';

// Simple Icons for brand/social media (official brand logos)
import {
  SiGithub,
  SiLinkedin,
} from 'react-icons/si';

import { IconName } from './icon-types';
import { ComponentType } from 'react';

// Type for icon components (both Tabler and react-icons)
type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

export const iconMap: Record<Exclude<IconName, 'princetonLogo'>, IconComponent> = {
  // Service Icons (Tabler - bolder strokes, professional look)
  database: IconDatabase,
  phone: IconPhone,
  sparkles: IconSparkles,
  zap: IconBolt,
  globe: IconWorld,
  gitBranch: IconGitBranch,
  layout: IconStack2,
  bot: IconRobot,
  code: IconCode,
  mobile: IconDeviceMobile,

  // UI Icons (Tabler)
  menu: IconMenu2,
  close: IconX,
  home: IconHome,
  info: IconInfoCircle,
  mail: IconMail,
  sun: IconSun,
  moon: IconMoon,
  chevronRight: IconChevronRight,
  chevronDown: IconChevronDown,
  arrowRight: IconArrowRight,
  check: IconCheck,
  calendar: IconCalendar,
  clock: IconClock,
  user: IconUser,
  users: IconUsers,
  settings: IconSettings,
  search: IconSearch,
  plus: IconPlus,
  minus: IconMinus,
  edit: IconEdit,
  trash: IconTrash,
  download: IconDownload,
  upload: IconUpload,
  link: IconLink,
  externalLink: IconExternalLink,
  copy: IconCopy,
  refresh: IconRefresh,
  send: IconSend,
  heart: IconHeart,
  star: IconStar,
  bell: IconBell,
  filter: IconFilter,
  sort: IconArrowsSort,
  grid: IconLayoutGrid,
  list: IconList,
  eye: IconEye,
  eyeOff: IconEyeOff,
  lock: IconLock,
  unlock: IconLockOpen,
  shield: IconShield,
  warning: IconAlertTriangle,
  alertCircle: IconAlertCircle,
  helpCircle: IconHelpCircle,
  checkCircle: IconCircleCheck,
  xCircle: IconCircleX,

  // Social/Brand Icons (Simple Icons - official brand logos)
  github: SiGithub,
  linkedin: SiLinkedin,
};
